// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgwbICWbvEIcRExt9W33xmWP2r7NAGdTM',
    appId: '1:841760585642:web:1d502928a4aed20e3e1dd3',
    messagingSenderId: '841760585642',
    projectId: 'notion-f50bf',
    authDomain: 'notion-f50bf.firebaseapp.com',
    storageBucket: 'notion-f50bf.firebasestorage.app',
    measurementId: 'G-F3D3TM5GWS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANOtt1Hqkgyavv3uDg2adnrAgy5HCR3G4',
    appId: '1:841760585642:android:8e32b64279251d8d3e1dd3',
    messagingSenderId: '841760585642',
    projectId: 'notion-f50bf',
    storageBucket: 'notion-f50bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHVLzPK6GRT_2YaLUb10WaFzBcEs3v6zE',
    appId: '1:841760585642:ios:1fd6e3f1317ba1dd3e1dd3',
    messagingSenderId: '841760585642',
    projectId: 'notion-f50bf',
    storageBucket: 'notion-f50bf.firebasestorage.app',
    iosClientId: '841760585642-1votcdfa34vlqgmdfbjjcj0m8fhcdqlm.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHVLzPK6GRT_2YaLUb10WaFzBcEs3v6zE',
    appId: '1:841760585642:ios:1fd6e3f1317ba1dd3e1dd3',
    messagingSenderId: '841760585642',
    projectId: 'notion-f50bf',
    storageBucket: 'notion-f50bf.firebasestorage.app',
    iosClientId: '841760585642-1votcdfa34vlqgmdfbjjcj0m8fhcdqlm.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgwbICWbvEIcRExt9W33xmWP2r7NAGdTM',
    appId: '1:841760585642:web:8bd1ca95204d41dc3e1dd3',
    messagingSenderId: '841760585642',
    projectId: 'notion-f50bf',
    authDomain: 'notion-f50bf.firebaseapp.com',
    storageBucket: 'notion-f50bf.firebasestorage.app',
    measurementId: 'G-JQ5X4Z92GL',
  );

}